#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.147                       #
#------------------------------------------------------------------------------#


WORKDIR = %cd%

CC = gcc.exe
CXX = gcc.exe
AR = ar.exe
LD = gcc.exe
WINDRES = windres.exe

INC = headers
CFLAGS = -Wall -DCURL_STATICLIB
RESINC = 
LIBDIR = 
LIB = 
LDFLAGS = -lcurl -lws2_32 -lwldap32

INC_DEBUG = $(INC)
CFLAGS_DEBUG = $(CFLAGS) -g -I
RESINC_DEBUG = $(RESINC)
RCFLAGS_DEBUG = $(RCFLAGS)
LIBDIR_DEBUG = $(LIBDIR)
LIB_DEBUG = $(LIB)
LDFLAGS_DEBUG = $(LDFLAGS)
SRCDIR_DEBUG = source
OBJDIR_DEBUG = obj\\Debug
DEP_DEBUG = 
OUT_DEBUG = bin\\Debug\\Product\ Manager.exe

INC_RELEASE = $(INC)
CFLAGS_RELEASE = $(CFLAGS) -O2
RESINC_RELEASE = $(RESINC)
RCFLAGS_RELEASE = $(RCFLAGS)
LIBDIR_RELEASE = $(LIBDIR)
LIB_RELEASE = $(LIB)
LDFLAGS_RELEASE = $(LDFLAGS) -s
OBJDIR_RELEASE = obj\\Release
DEP_RELEASE = 
OUT_RELEASE = bin\\Release\\Product\ Manager.exe

OBJ_DEBUG = $(OBJDIR_DEBUG)\\check_updates.o $(OBJDIR_DEBUG)\\connection_status.o $(OBJDIR_DEBUG)\\ftpget.o $(OBJDIR_DEBUG)\\main.o $(OBJDIR_DEBUG)\\process.o $(OBJDIR_DEBUG)\\str_fnt.o $(OBJDIR_DEBUG)\\upgrade.o $(OBJDIR_DEBUG)\\usb2serial_read_w32.o

OBJ_RELEASE = $(OBJDIR_RELEASE)\\check_updates.o $(OBJDIR_RELEASE)\\connection_status.o $(OBJDIR_RELEASE)\\ftpget.o $(OBJDIR_RELEASE)\\main.o $(OBJDIR_RELEASE)\\process.o $(OBJDIR_RELEASE)\\str_fnt.o $(OBJDIR_RELEASE)\\upgrade.o $(OBJDIR_RELEASE)\\usb2serial_read_w32.o

all: debug release

clean: clean_debug clean_release

before_debug: 
	cmd /c if not exist bin\\Debug md bin\\Debug
	cmd /c if not exist $(OBJDIR_DEBUG) md $(OBJDIR_DEBUG)

after_debug: 

debug: before_debug out_debug after_debug

out_debug: before_debug $(OBJ_DEBUG) $(DEP_DEBUG)
	$(LD) $(LIBDIR_DEBUG) -o $(OUT_DEBUG) $(OBJ_DEBUG)  $(LDFLAGS_DEBUG) $(LIB_DEBUG)

$(OBJDIR_DEBUG)\\check_updates.o: $(SRCDIR_DEBUG)\\check_updates.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c $(SRCDIR_DEBUG)\\check_updates.c -o $(OBJDIR_DEBUG)\\check_updates.o

$(OBJDIR_DEBUG)\\connection_status.o: $(SRCDIR_DEBUG)\\connection_status.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c $(SRCDIR_DEBUG)\\connection_status.c -o $(OBJDIR_DEBUG)\\connection_status.o

$(OBJDIR_DEBUG)\\ftpget.o: $(SRCDIR_DEBUG)\\ftpget.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c $(SRCDIR_DEBUG)\\ftpget.c -o $(OBJDIR_DEBUG)\\ftpget.o

$(OBJDIR_DEBUG)\\main.o: $(SRCDIR_DEBUG)\\main.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c $(SRCDIR_DEBUG)\\main.c -o $(OBJDIR_DEBUG)\\main.o

$(OBJDIR_DEBUG)\\process.o: $(SRCDIR_DEBUG)\\process.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c $(SRCDIR_DEBUG)\\process.c -o $(OBJDIR_DEBUG)\\process.o

$(OBJDIR_DEBUG)\\str_fnt.o: $(SRCDIR_DEBUG)\\str_fnt.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c $(SRCDIR_DEBUG)\\str_fnt.c -o $(OBJDIR_DEBUG)\\str_fnt.o

$(OBJDIR_DEBUG)\\upgrade.o: $(SRCDIR_DEBUG)\\upgrade.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c $(SRCDIR_DEBUG)\\upgrade.c -o $(OBJDIR_DEBUG)\\upgrade.o

$(OBJDIR_DEBUG)\\usb2serial_read_w32.o: $(SRCDIR_DEBUG)\\usb2serial_read_w32.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c $(SRCDIR_DEBUG)\\usb2serial_read_w32.c -o $(OBJDIR_DEBUG)\\usb2serial_read_w32.o

clean_debug: 
	cmd /c del /f $(OBJ_DEBUG) $(OUT_DEBUG)
	cmd /c rd bin\\Debug
	cmd /c rd $(OBJDIR_DEBUG)

before_release: 
	cmd /c if not exist bin\\Release md bin\\Release
	cmd /c if not exist $(OBJDIR_RELEASE) md $(OBJDIR_RELEASE)

after_release: 

release: before_release out_release after_release

out_release: before_release $(OBJ_RELEASE) $(DEP_RELEASE)
	$(LD) $(LIBDIR_RELEASE) -o $(OUT_RELEASE) $(OBJ_RELEASE)  $(LDFLAGS_RELEASE) $(LIB_RELEASE)

$(OBJDIR_RELEASE)\\check_updates.o: check_updates.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c check_updates.c -o $(OBJDIR_RELEASE)\\check_updates.o

$(OBJDIR_RELEASE)\\connection_status.o: connection_status.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c connection_status.c -o $(OBJDIR_RELEASE)\\connection_status.o

$(OBJDIR_RELEASE)\\ftpget.o: ftpget.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c ftpget.c -o $(OBJDIR_RELEASE)\\ftpget.o

$(OBJDIR_RELEASE)\\main.o: main.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c main.c -o $(OBJDIR_RELEASE)\\main.o

$(OBJDIR_RELEASE)\\process.o: process.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c process.c -o $(OBJDIR_RELEASE)\\process.o

$(OBJDIR_RELEASE)\\str_fnt.o: str_fnt.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c str_fnt.c -o $(OBJDIR_RELEASE)\\str_fnt.o

$(OBJDIR_RELEASE)\\upgrade.o: upgrade.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c upgrade.c -o $(OBJDIR_RELEASE)\\upgrade.o

$(OBJDIR_RELEASE)\\usb2serial_read_w32.o: usb2serial_read_w32.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c usb2serial_read_w32.c -o $(OBJDIR_RELEASE)\\usb2serial_read_w32.o

clean_release: 
	cmd /c del /f $(OBJ_RELEASE) $(OUT_RELEASE)
	cmd /c rd bin\\Release
	cmd /c rd $(OBJDIR_RELEASE)

.PHONY: before_debug after_debug clean_debug before_release after_release clean_release

